---
- name: In-Memory Inventory
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
  #  guid: "{{ lookup('ENV','GUID') }}"
  #  home: "{{ lookup('ENV','HOME') }}"
    internal_domain: "example.com"
  tasks:
    - name: Collection instance info
      os_server_info:
        cloud: "{{ guid }}-project"
      register: instances

    - name: Build In-Memory inventory
      add_host:
        host: "{{ instance.name }}.{{ internal_domain }}"
        group: "{{ instance.metadata.AnsibleGroup }}"
        ansible_host: "{{ instance.private_v4 }}"
        ssh_private_key_file: "{{ home }}/.ssh/{{ guid }}key.pem"
      when: instance.metadata.AnsibleGroup == "osp_instances"
      loop: "{{ instances.openstack_servers }}"
      loop_control:
        loop_var: instance

- name: Print current hosts
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - debug: var=groups

- name: Play to automate process
  hosts: all
  vars:
    service_user_name: devops
    service_user_password: redhat
    ssh_key_path: /home/devops/.ssh/
    ssh_key_name: id_rsa
    satellite_activationkey: gpte-labs-rhel8
    satellite_org: prod

  tasks:
    - name: Gather network facts
      setup:
        gather_subset:
          - 'network'
      delegate_facts: true
      delegate_to: localhost
      connection: local

    - name: DNS IP updated
      lineinfile:
        state: present
        path: /etc/sysconfig/network-scripts/ifcfg-eth0
        line: "{{ item }}"
      loop:
        - PEERDNS=no
        - DNS1={{ hostvars.localhost.ansible_default_ipv4.address }}
      register: network_update
    
    - name: Update /etc/hosts
      lineinfile:
        state: present
        path: /etc/hosts
        line: 192.168.50.141 satellite.example.com
        
    - name: restart network manager
      service:
        name: NetworkManager
        state: restarted
      when: network_update.changed | bool

    - name: install katello-ca-consumer package
      yum:
        name: http://satellite.example.com/pub/katello-ca-consumer-latest.noarch.rpm
        state: present
        disable_gpg_check: true

    - name: register system and attach subs
      redhat_subscription:
        state: present
        activationkey: "{{ satellite_activationkey }}"
        org_id: "{{ satellite_org }}"
        auto_attach: true

    - name: Create Service User Account
      user:
        name: "{{ service_user_name }}"
        comment: Service User Account
        password: "{{ service_user_password | default(omit) | password_hash('sha512') }}"
        state: present

    - name: enable sudo privilege
      copy:
        content: "{{ service_user_name }} ALL=(ALL) NOPASSWD:ALL"
        dest: '/etc/sudoers.d/{{ service_user_name }}-service-account'

    - name: check if ssh key exist
      stat:
        path: "{{ ssh_key_path }}/{{ ssh_key_name }}"
      register: ssh_pub_key
      delegate_to: localhost

    - name: Generate ssh key pair
      when: not ssh_pub_key.stat.exists
      openssh_keypair:
        path: "{{ ssh_key_path }}/{{ ssh_key_name }}"
        owner: devops
        group: users
        mode: 0400
      delegate_to: localhost
      connection: local

    - name: add public key
      authorized_key:
        user: "{{ service_user_name }}"
        key: "{{ lookup('file', '{{ ssh_key_path }}/{{ ssh_key_name }}.pub') }}"
        state: present

    - name: Disable root login
      lineinfile:
        line: PermitRootLogin no
        regexp: '^ *PermitRootLogin'
        path: /etc/ssh/sshd_config
      notify: restart ssh

    - name: disable password based authentication
      lineinfile:
        line: PasswordAuthentication no
        regexp: '^ *PasswordAuthentication'
        path: /etc/ssh/sshd_config
      notify: restart ssh

  handlers:
    - name: restart ssh
      service:
        name: sshd
        state: restarted
